name: Greet Everybody
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./hello-world-action
      with:
        who-to-greet: 'Octocat'
      id: hello
    - run: echo "The time was ${{ steps.hello.outputs.time }}"